---
- name: nginx install & start services
  hosts: ansible_clients
  remote_user: root
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: create content
    copy:
       content: "welcome" 
       dest: /var/www/html/index.html
