---
#configuring httpd.conf and sending sample html file
- name: http.conf file
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify:
     restart apache service

- name: send index.html
  copy: src=index.html dest=/home/reddy/index.html
